"""empty message

Revision ID: 2c07734fdd7b
Revises: 
Create Date: 2023-07-06 15:19:03.719377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c07734fdd7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('real_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.Enum('user', 'judge', 'admin', 'superadmin', 'athlete'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('real_name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_type', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('judge',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=200), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('type_of_jury', sa.Enum('major', 'normal'), nullable=True),
    sa.ForeignKeyConstraint(['category_name'], ['category.name'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('poomsae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strength_and_velocity', sa.Integer(), nullable=True),
    sa.Column('rythm_and_coordenation', sa.Integer(), nullable=True),
    sa.Column('energy_expression', sa.Integer(), nullable=True),
    sa.Column('technical_component', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('athlete_poomsae',
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('poomsae_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.ForeignKeyConstraint(['poomsae_id'], ['poomsae.id'], ),
    sa.PrimaryKeyConstraint('athlete_id', 'poomsae_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('athlete_poomsae')
    op.drop_table('poomsae')
    op.drop_table('judge')
    op.drop_table('athlete')
    op.drop_table('user')
    op.drop_table('tournament')
    op.drop_table('category')
    # ### end Alembic commands ###
